### ISSUE TITLE
ErrorException on magento composer install 

### ISSUE THREAD

**Issue by dolito** [Nosto/nosto-magento-extension#138]
composer.json - require:
  "nosto/nosto-magento-extension": "dev-master"

bin/composer.phar update --no-dev

 [ErrorException]
 Source ../vendor/nosto/nosto-magento-extension/lib/nosto/* does not exist

**Comment by dolito** [comment]
I think your modman file is the problem:
lib/nosto/* lib/nosto/
there is no lib/nosto in this module

**Comment by hannunosto** [comment]
Hi @dolito, you probably need to run ```composer update```. We have changed the vendor directory in composer.json to ```lib``` instead of ```vendor```. https://github.com/Nosto/nosto-magento-extension/blob/master/composer.json#L23

**Comment by dolito** [comment]
that's what I did ..
now I get a dependencies not resolvable error ..

here's my composer.json, could you just try it once, I tried it in any recent version, dev no-dev, etc..

I still think what you're trying to do just doesnt work, lib folder here is not the magento lib folder .. or am I horribly wrong?

thanks for your help :)

[composer.json.txt](https://github.com/Nosto/nosto-magento-extension/files/279278/composer.json.txt)

**Comment by dannydnz** [comment]
I had the same issue.

My project structure was 

-project-root/
       - public/ (this is mage root and where the composer.json sits for my project)
       - vendor/ this is where vendor dir sits

When I ran composer update the following error occured.
````
Source ......../project-root/vendor/nosto/nosto-magento-extension/lib/nosto/* does not exist
````
I was able to resolve this by navigating to
````
cd .........../project-root/vendor/nosto/nosto-magento-extension/
````
And executed 
````
composer install
````

This installed the required sdk in the location 
````
................/project-root/vendor/nosto/nosto-magento-extension/lib
````

I then ran compose update for the entire project and this completed without any errors.

Hope this helps anyone else in this situation.

**Comment by dio5** [comment]
Same problem happening here, with the same structure as mentioned by dannydnz.
