### ISSUE TITLE
Add support for multi-currency environment and exchange rates

### ISSUE THREAD

**Issue by romainsassareu** [Nosto/nosto-magento-extension#15]
The implementation of the multi-currency no longer relies on variant tagging but instead uses the new exchange-rates API.

Right after the account-creation API call has been made or the account has been connected using OAuth, we will make an API call to Nosto to push the exchange-rates over the API.

1. In order or access the exchange rates API, we will need to change the OAuth scopes to include the exchange-rates scope and similarly for the account-creation API call.

2. We would also be adding an observer for the exchange-rates inside Magento to push the exchange-rates over the API, every time the exchange-rates are updated.

```
{
         "rates": {
             "SEK": {
                 "rate": 9.3,
                 "price_currency_code": "SEK"
             },
             "USD": {
                 "rate": 1.3,
                 "price_currency_code": "USD"
             }
         },
         "valid_until": "2015-02-27T12:00:00Z"
    }
```

3.  All the tagging across the site should also list the current currency in use while all the prices should be in the base currency. `<div class="nosto_price_variation" style="display:none">EUR</div>`.

4. The product-tagging must include a new attribute that identifies the base variant `<span class="variation_id">EUR</span>`

All the orders (via the API and the order-confirmation page), the cart tagging and the will always be reported in the base-currency.

Also the product and order-import will be reported in the base-currency.

Right after the account-creation API call is made, all the exchange rates should be posted to the exchange-rates API so the merchant can preview his site.

Also, the exchange rates should be available as a front-controller with the API_* token so we can periodically pull it.

---

In the event that the merchant is using exchange rates with a expiration timestamp, then the recommendation template should be updated to always reference the product price as `$!product.price` instead of `$product.price.

**Comment by Floddy** [comment]
Looks like a valid approach. Some thoughts:

* I've actually not been able to find an event that triggers on an updated currency rate. If this is not possible, a cron job would probably work, along with a manual update button. Also, the cron job would have an on/off setting, and a setting for timestamp. The cron setting to be able to set the cron job to be ran after the daily rate fetching (configurable in magento) - with the ability to turn this off and update manually, in case the customer is using manual rates. A setting for lifetime would probably also be good.

* If the website has previously been tagged "the old way" with all the variation div's - will there be any conflicts with this collected data in Nosto, and the new "currency rates"?

**Comment by petterisusi** [comment]
If you start to use the currency rates, the variation divs will be ignored altogether. Only the base variation of the product -- the variation that has the base price -- will be used.

**Comment by kryysler** [comment]
Added in branch release/3.0.0
