### ISSUE TITLE
Adding more data to the product tagging

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#16]
Add the full description and a tag called ?? to identify products that can be added to cart directly.
Also add the full-description of the product to the short description.

**Comment by kryysler** [comment]
In the Magento example data, the "short-description" is longer than the "full-description". Should we concat them and include both or what?

**Comment by mridang** [comment]
Yeah, let's concatenate them and send them both. We can concatenate them with a `<br />`

**Comment by kryysler** [comment]
Added to develop branch
