### ISSUE TITLE
Product after save observer does not handle store context correctly

### ISSUE THREAD

**Issue by kryysler** [Nosto/nosto-magento-extension#29]
The store context is currently all stores regardless of the scope the product is modified in. This results in sending a re-crawl request to all existing Nosto accounts (i.e. for all stores).

How do we get only the stores a product has been modified for in the event observer for `catalog_product_save_after`?

**Comment by mridang** [comment]
http://magento.stackexchange.com/questions/64519/how-can-i-get-the-correct-store-context-in-the-product-save-observer

**Comment by mridang** [comment]
As discussed, the creation/deletion API call with be per-store while the update will happen for all the stores (simpler)

**Comment by kryysler** [comment]
Added to develop branch.

create/update will happen for all stores the product is available in, while delete will always happen for all stores as it seems that it is deleted for each store regardless of the store scope switcher value.
