### ISSUE TITLE
Show the original OAuth error as returned by Nosto instead of the Magento one

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#32]
Currently we show a basic error in Magento and the real OAuth error goes into the logs. We should be showing the `description` parameter as returned by Nosto in OAuth.

**Comment by kryysler** [comment]
The extension does not show the message, but passes a message code to the iframe. We would need to handle this on in the iframe, but also need to add some info so we know what to show. Ideas?
