### ISSUE TITLE
Support for picking the correct image type e.g. base, thumbnail, etc.

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#33]
There should be a setting to choose which product image to use (Base, Small, Thumbnail). One of our customers uses tall rectangular images for his base image but square, better cropped images for his small and thumbnail images because they look better in small squares in a grid.

THis needs to be in an advanced configuration section and not a part of the IFrame UI.

**Comment by kryysler** [comment]
Added to develop branch
