### ISSUE TITLE
Add support for account-specific subdomains for the IFrame

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#38]
First the SSO API call needs to be made to `/hub/{platform}/load/{email}`

Instead of making the SSO authorization call to `my.nosto.com/auth/sso/{username}/{code}`, the call should be made to `my.nosto.com/hub/{platform}/{merchant}/{username}/{code}` (without the `r` parameter) which will automatically redirect you to the correct subdomain.

**Comment by kryysler** [comment]
Added to develop branch
