### ISSUE TITLE
Backwards compatibly for overridden templates can be broken in the release

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#46]
The merchant had extended `product.phtml` and was using the `Date.php` helper class. Since this file was removed in 3.0.0, all merchants that possibly might have extended the `product.phtml` file might get broken PDPs.

**Comment by kryysler** [comment]
This is not a bug. 3.0.0 is a major release, and thus will break backwards compatibility. Classes have been refactored, removed, added. Templates have been re-done. Basically if you have overridden any template or class, it won't work out-of-the-box after upgrading.
