### ISSUE TITLE
Send settings periodically along with the exchange rates

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#47]
To make it easier, we could also periodically send the account-settings (i.e. currency formats) when we send the exchange rates.

Merchants often make changes to the currency settings and need to be told to explicitly click the button..

This wouldn't cause any harm and would reduce the number of support requests pertaining the mismatch of currency formats in the Nosto recommendations and the Magento backend.

**Comment by kryysler** [comment]
Is this really a good idea? The currency settings won't be changed periodically, or even that often. And when/if they are changed, you want them the be applied immediately, and not wait for the cron to run. The use case is not the same as for the exchange rates.
