### ISSUE TITLE
Fix the multi-variant and multi-currency tagging

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento-extension#68]
- [x] Remove this from each product `<span class="variation_id">EUR</span>` when using MV.(edited)
- [x] Remove this `<div class="nosto_price_variation" style="display:none">EUR</div>` when using MV and instead use `<div class="nosto_variation" style="display:none">EUR</div>`
- [x] Disable MV and MC when no multiple currencies.

**Comment by hannunosto** [comment]
Fixed develop
